fixed JENKINS-39441
hpsa/hp-application-automation-tools-plugin pull request #148
Opened 2017-01-04 06:36 UTC by jackzenko

HP plugin now sets build status to failure before returning.

2017-01-08 05:56 UTC, YafimK reviewed
- [ ] Update headline to state clear PR subject.
- [ ] Add link to Jenkins issue.
- [ ] Add JavaDoc to the RunFromAlmBuilder for future developers.

2017-01-08 06:02 UTC, YafimK commented
Please review other places in perform which should exit in failure / aborted state such as in line 266: when the build is aborted by the user.

An ALM server is selected when creating a new Job - why can't we check it there, i.e "doCheckAlmServer"?

2017-01-08 06:03 UTC, YafimK requested changes
Please review and fix issues stated in the comments

2017-01-08 08:16 UTC, YafimK commented
test this PR

2017-01-09 08:47 UTC, jackzenko commented
1. Update headline to state clear PR subject. (done)
2. Add link to Jenkins issue. (done)
3. Add JavaDoc to the RunFromAlmBuilder for future developers. (done)
4. Please review other places in perform which should exit in failure / aborted state such as in line 266: when the build is aborted by the user. (the status was set in line 232 as ABORTED)
5. to align the work flow, its much better to set build result status here.

2017-03-22 16:04 UTC, YafimK approved these changes

2017-03-22 16:04 UTC, YafimK commented
approve to merge

2017-03-22 16:05 UTC, merged