Support HTTPS protocol for PCS
hpsa/hp-application-automation-tools-plugin pull request #155
Opened 2017-01-19 14:22 UTC by bamh

Added ability to start a run on a secured Performance Center server,
by checking the option: 'Use HTTPS Protocol' on the job configuration.

* Please ignore the changes on the POM file

2017-01-21 09:41 UTC, YafimK requested changes
- [  ] Rebase. undo any needed changes.
- [  ] Add JavaDoc to any undocumented methods and files.

2017-01-22 16:22 UTC, bamh commented
I added some comments to the needed files.
The Mocks and Tests don't need.

2017-01-23 06:03 UTC, YafimK commented
Approved for test build

2017-01-23 07:04 UTC, YafimK commented
Approved for test build

2017-01-23 10:02 UTC, bamh commented on src/main/java/com/hp/application/automation/tools/pc/PcRestProxy.java
> +    private PrintStream logger;
It is being used see next line:
this.logger = logger;

2017-01-23 10:03 UTC, bamh commented on src/main/java/com/hp/application/automation/tools/run/PcBuilder.java
> +    private final boolean HTTPSProtocol;
again, being used:
 this.HTTPSProtocol = HTTPSProtocol;

2017-01-23 16:32 UTC, YafimK commented
Please add Jira ticket as required in the PR template

2017-01-26 10:58 UTC, YafimK commented
Approved for test build

2017-01-30 08:00 UTC, YafimK commented
Approved for test build

2017-01-30 08:04 UTC, YafimK approved these changes

2017-03-22 16:07 UTC, merged