Support executing SSE on ALM SaaS
hpsa/hp-application-automation-tools-plugin pull request #164
Opened 2017-03-07 08:33 UTC by Roy-Lu

Support executing SSE on ALM SaaS
JIRA Ticket: JENKINS-42295

2017-03-22 16:14 UTC, YafimK requested changes
Please add proper JavaDoc to the classes - at least some General info  on existing classes

2017-03-22 16:14 UTC, YafimK commented on src/main/java/com/hp/application/automation/tools/rest/RestClient.java
> -import java.net.URLConnection;
Please avoid such changes - explicit import makes life easier to catch import issues

2017-03-22 16:14 UTC, YafimK commented on src/main/java/com/hp/application/automation/tools/sse/sdk/RunManager.java
>   * @author Effi Bar-She'an
Please add proper JavaDoc to this file

2017-03-22 16:14 UTC, YafimK commented on src/main/java/com/hp/application/automation/tools/results/service/AlmRestTool.java
>  public class AlmRestTool {
Please add JavaDoc

2017-04-07 06:03 UTC, YafimK commented
approved for test build

2017-04-10 05:21 UTC, YafimK commented
approved for test build

2017-04-10 05:50 UTC, Roy-Lu commented
I think the hpebot is too strict.

2017-04-10 06:08 UTC, Roy-Lu commented
MAJOR AuthenticationTool.java#L68: Either log or rethrow this exception. rule
It is logged.
MAJOR RestAuthenticator.java#L147: Remove this unused private "isAlreadyAuthenticated" method. rule
MAJOR RestAuthenticator.java#L171: Remove this unused private "logLoggedInSuccessfully" method. rule
MAJOR RestAuthenticatorSaas.java#L106: Remove this unused private "logLoggedInSuccessfully" method. 
These methods are used.

2017-04-10 20:26 UTC, YafimK approved these changes

2017-04-10 20:26 UTC, YafimK commented
approve for test build

2017-04-11 09:46 UTC, merged